name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Prepare Artifact
      run: |
        sudo chown -R $USER:$USER _site
        ./scripts/remove_extra.sh _site
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: website.tar.gz
        path: _site/


